apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-oracle
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: connect-oracle
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: connect-oracle
    spec:
      containers:
      - name: oracle
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        command: ["connect"]
        args:
        - "--disable-telemetry=$(DISABLE_TELEMETRY)"
        - "--host=$(HOST)"
        - "--log-file=/dev/null"
        - "--log-std-out-level=$(LOG_STD_OUT_LEVEL)"
        {{- if .Values.env.MARKET_CONFIG_PATH }}
        - "--market-config-path=$(MARKET_CONFIG_PATH)"
        {{- end }}
        - "--market-map-endpoint=$(MARKET_MAP_ENDPOINT)"
        - "--marketmap-provider=$(MARKETMAP_PROVIDER)"
        - "--max-price-age=$(MAX_PRICE_AGE)"
        - "--metrics-enabled=$(METRICS_ENABLED)"
        - "--metrics-prometheus-address=$(METRICS_PROMETHEUS_ADDRESS)"
        - "--mode=$(MODE)"
        - "--oracle-config=$(ORACLE_CONFIG)"
        - "--port=$(PORT)"
        - "--pprof-port=$(PPROF_PORT)"
        - "--run-pprof=$(RUN_PPROF)"
        - "--update-interval=$(UPDATE_INTERVAL)"
        - "--update-market-config-path=$(UPDATE_MARKET_CONFIG_PATH)"
        - "--validation-period=$(VALIDATION_PERIOD)"
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        ports:
        - name: pprof
          containerPort: {{ .Values.ports.pprof | default 6060 }}
        - name: metrics
          containerPort: {{ .Values.ports.metrics | default 8002 }}
        - name: http
          containerPort: {{ .Values.ports.http | default 8080 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
