apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-oracle
spec:
  type: ClusterIP
  selector:
    app: oracle
  ports:
  - name: http
    port: {{ .Values.service.port | default 8080 }}
    targetPort: {{ .Values.service.targetPort | default 8080 }}