{
 "title": "Connect sidercar basic info",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(side_car_connect_build_info,service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service version",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (service, version)  (side_car_connect_build_info)",
     "legendFormat": "{{service}} {{version}}"
    }
   ]
  },
  {
   "title": "RPC status codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "side_car_api_rpc_status_code{service=~\"$service\"}",
     "legendFormat": "{{service}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Internal Status Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "side_car_api_response_internal_status{service=~\"$service\"}",
     "legendFormat": "{{service}} {{internal_status}}"
    }
   ]
  }
 ]
}