replicaCount: 1

image:
  repository: skip-mev/connect-oracle-with-blockchain
  tag: 2eeeef7-dirty
  pullPolicy: IfNotPresent

env:
  DISABLE_TELEMETRY: "false"
  HOST: "0.0.0.0"
  LOG_STD_OUT_LEVEL: "info"
  MARKET_CONFIG_PATH: ""
  MARKET_MAP_ENDPOINT: "blockchain:9090"
  MARKETMAP_PROVIDER: "marketmap_api"
  MAX_PRICE_AGE: "2m0s"
  METRICS_ENABLED: "true"
  METRICS_PROMETHEUS_ADDRESS: "0.0.0.0:8002"
  MODE: "exec"
  ORACLE_CONFIG: ""
  PORT: "8080"
  PPROF_PORT: "6060"
  RUN_PPROF: "true"
  UPDATE_INTERVAL: "250000000"
  UPDATE_MARKET_CONFIG_PATH: ""
  VALIDATION_PERIOD: "10m0s"

ports:
  pprof: 6060
  metrics: 8002
  http: 8080

resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /connect/oracle/v2/version
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /connect/oracle/v2/version
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

service:
  port: 8080
  targetPort: 8080
